services:
  qbittorrent:
    image: ghcr.io/er1c-zh/qbittorrent-enhanced:latest
    container_name: qbittorrent
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Shanghai
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
